### ISSUE TITLE
 when i run basicagent.py happen error

### ISSUE THREAD

**Issue by ggstar00** [Morphlng/MACarla-Gym#1]
Traceback (most recent call last):
  File "/home/ggstar/pythonproject/MACarla-Gym-main/examples/basic_agent.py", line 5, in <module>
    env = gym.make("HomoNcomIndePOIntrxMASS3CTWN3-v0")
  File "/home/ggstar/anaconda3/envs/marllib/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/ggstar/anaconda3/envs/marllib/lib/python3.8/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/home/ggstar/anaconda3/envs/marllib/lib/python3.8/site-packages/gym/envs/registration.py", line 89, in make
    cls = load(self.entry_point)
  File "/home/ggstar/anaconda3/envs/marllib/lib/python3.8/site-packages/gym/envs/registration.py", line 27, in load
    mod = importlib.import_module(mod_name)
  File "/home/ggstar/anaconda3/envs/marllib/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggstar/pythonproject/MACarla-Gym-main/src/macad_gym/envs/__init__.py", line 1, in <module>
    from macad_gym.carla.multi_env import MultiCarlaEnv
  File "/home/ggstar/pythonproject/MACarla-Gym-main/src/macad_gym/carla/multi_env.py", line 28, in <module>
    from macad_gym.core.data.simulator import Simulator, CARLA_OUT_PATH
  File "/home/ggstar/pythonproject/MACarla-Gym-main/src/macad_gym/core/data/__init__.py", line 4, in <module>
    from macad_gym.core.data.simulator import Simulator
  File "/home/ggstar/pythonproject/MACarla-Gym-main/src/macad_gym/core/data/simulator.py", line 64, in <module>
    class Weather:
  File "/home/ggstar/pythonproject/MACarla-Gym-main/src/macad_gym/core/data/simulator.py", line 68, in Weather
    0: carla.WeatherParameters.ClearNoon,
AttributeError: module 'carla' has no attribute 'WeatherParameters'

进程已结束,退出代码1

**Comment by ggstar00** [comment]
In fact I have configured the environment as per your instructions

**Comment by ggstar00** [comment]
when i use marllib,happen  macad      | Error          | No module named 'agents'            | envs/base_env/config/macad.yaml     | envs/base_env/macad.py

**Comment by Morphlng** [comment]
> when i use marllib,happen macad | Error | No module named 'agents' | envs/base_env/config/macad.yaml | envs/base_env/macad.py

This problem is due to the PYTHONPATH environment configuration. This fork of Macad-Gym has done a lot of modification, including the re-design of `PathTracker`. We are currently using `BasicAgent` from Carla's PythonAPI as a replacement.

**Comment by ggstar00** [comment]
I used carla==0.9.13,  I set env,but                                                                                                                                              | macad      | Error          | No module named 'agents'            | envs/base_env/config/macad.yaml     | envs/base_env/macad.py     |
+------------+----------------+-------------------------------------+-------------------------------------+----------------------------+
Traceback (most recent call last):
  File "marl/main.py", line 55, in <module>
    run_cc(config_dict)
  File "/home/ggstar/pythonproject/MACarla-Gym-main/MARLlib/marl/algos/run_cc.py", line 44, in run_cc
    raise ValueError(
ValueError: environment "macad" not installed properly or not registered yet, please see the Error_Log below

**Comment by ggstar00** [comment]
According to what you said, I can already run it, but when it runs, it will exceed the memory limit. My memory is 16gb. How to run carla with low quality

**Comment by Morphlng** [comment]
> According to what you said, I can already run it, but when it runs, it will exceed the memory limit. My memory is 16gb. How to run carla with low quality

MARLlib is still a work in progress, I can't guarantee a successful usage for now. If you're having trouble with memory exceeding (GPU memory), it's most likely that you have set the observation shape too high. Try switch `res_x` and `res_y` to 84, 84 instead in [macad.yaml](https://github.com/Morphlng/MARLlib/blob/main/envs/base_env/config/macad.yaml).

If you really want to use a low-quality mode of Carla, then you'll have to manually add `-quality-level=Low` in here:
https://github.com/Morphlng/MACarla-Gym/blob/19e279f64756e0d25e3768de7b6496696172faa5/src/macad_gym/core/data/simulator.py#L214-L227

**Comment by ggstar00** [comment]
when I set low-quality,  carla exit                                                                                                                                    
(pid=6188) Malloc Size=65538 LargeMemoryPoolOffset=65554 
(pid=6188) Malloc Size=131160 LargeMemoryPoolOffset=196744 
(pid=6188) Malloc Size=131160 LargeMemoryPoolOffset=327928 
(pid=6188) Segmentation fault (core dumped)

**Comment by ggstar00** [comment]
I have run 101 iters, but the effect is very poor. How many rounds will have a better effect

**Comment by Morphlng** [comment]
> I have run 101 iters, but the effect is very poor. How many rounds will have a better effect

That depends on the algorithm and the network structure. In terms of `HomoNcomIndePOIntrxMASS3CTWN3`, we haven't successfully trained that scenario either. According to the result given in the [original paper](https://arxiv.org/abs/1911.04175), at least 8M step (500 step each iter) is needed to achieve a useful result.

If there's no more error for you to run the environment, I'll close the comment.

Also, the behavior of this fork is still unstable, I suggest using the main branch at https://github.com/praveen-palanisamy/macad-gym

**Comment by ggstar00** [comment]
Thank you. How can I use tensorboard to visualize this result

**Comment by Morphlng** [comment]
> Thank you. How can I use tensorboard to visualize this result

Assuming you have followed all the tutorial to setup the environment, you should have a conda env called "marllib" and all the library installed properly. Then, follow these steps:

```bash
conda activate marllib
pip install tensorboard

tensorbard --logdir=~/ray_results/{your_experiment_folder_name}
```
